### ISSUE TITLE
Project 1 Peer Review - Team Epsilon

### ISSUE THREAD

**Issue by chanakyaken** [airavata-courses/garuda#75]
Hi Team,

I tried to set up your Project on my System which is a MAC running (Monterey v12.1) in which port 5000 is being already used by the OS and I saw that your api gateway runs on PORT 5000, so I tried to update it to an open port in my system (Port 6000) but it still didn't work and then I found out that you have written the port in  files other than the configuration files and even after changing them it didn't work.

I would suggest not to write PORT details directly in the code like it was done in garuda.apigateway/server.py and you can also try to look what can be done so that such issues with PORTS can be handled with less changes or changes at a single place like changing the port in docker-compose.yml maybe should change the PORT dependency everywhere.
You can have a look at "Environment" tag for docker-compose.

<img width="1440" alt="Screen Shot 2022-02-09 at 10 18 32 PM" src="https://user-images.githubusercontent.com/94653406/153330794-93b899f9-5ae4-4402-96a1-a2d954a3ffb2.png">

<img width="1440" alt="Screen Shot 2022-02-09 at 10 27 53 PM" src="https://user-images.githubusercontent.com/94653406/153331608-3df9ca1c-84cc-434b-a235-5bba570c41b3.png">

**Comment by pranavacharya** [comment]
Thanks for your review ! 

We were planning to move the ports and host name outside to environment variable in the next spring. Your review gave a good excuse to open a feature request now. 

Regarding your CORS issue, we had added CORS specific header at server side. Maybe the front end is requesting on port 5000 but since you made the server listen on port 6000 a change on the client side was also needed. This can be managed easily once we move all the ports and hostname to env variables as you suggested.

Thanks for the review.

**Comment by rishi1596** [comment]
@chanakyaken Much appreciated.
For time being could you follow this [link](https://anandtripathi5.medium.com/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c) 
So that you could run our project.

Thanks.

**Comment by pranavacharya** [comment]
Issue opened in #76
